ARG NODE_VERSION=14.20-alpine3.16
FROM node:${NODE_VERSION} AS base


FROM base as install
WORKDIR /app
COPY package.json package-lock.json .
RUN npm install

COPY ./ ./


FROM install AS builder
RUN npm run build


FROM base
ARG USER_ID=1000

WORKDIR /app
COPY --from=builder --chown=${USER_ID}:0 /app/package.json /app/package-lock.json ./
COPY --from=builder --chown=${USER_ID}:0 /app/build ./build
# COPY --from=builder --chown=${USER_ID}:0 /app/node_modules ./node_modules

RUN npm install serve

USER ${USER_ID}
EXPOSE 3000

CMD ["npm", "run", "start:prod"]

